### ISSUE TITLE
FakeClaim tweets content

### ISSUE THREAD

**Issue by awezmm** [cuilimeng/CoAID#1]
Have the tweets in the dataset been manually labeled as ClaimFake or ClaimTrue? 
A lot of tweets in the 05-01-2020/ClaimFakeCOVID-19_tweets.csv seem to be referencing fake claims but don't necessarily claim something fake.

For instance, the fourth tweet in that file with id = 1242461115616866304 at link https://twitter.com/sivadigitalart/status/1242461115616866304  has the content:
```
#Corona Myth & Reality.

Myth: Only older adults and young people are at risk.

Reality: People of all ages can be infected by the #CoronaVirus however older people & people with medical conditions might be more likely to become severely ill with the virus
#SatyHome #StayPositive
```
It doesn't seem that the tweet author here is claiming anything fake, but rather is disproving a fake myth. Are the tweets in ClaimFakeCOVID-19_tweets tweets that only "mention" fake claims, but could still be disproving them?

Thanks

**Comment by cuilimeng** [comment]
The tweets in ClaimFakeCOVID-19_tweets are tweets that mention the fake claims.
