### ISSUE TITLE
Full dataset

### ISSUE THREAD

**Issue by FrankFundel** [cuilimeng/CoAID#5]
Does someone have the fully downloaded/crawled dataset of tweets? Would be much more efficent to just add a column for the tweet content. Also many tweets were deleted or the user got suspended over time.

**Comment by cuilimeng** [comment]
According to Twitter's developer terms (https://developer.twitter.com/en/developer-terms/policy), I may only distribute Tweet IDs, Direct Message IDs, and/or User IDs. Sorry for the inconvenience.
